Repository espressif/esp32-arduino-lib-builder, pull requests merged in 2025-06, with the labels that each got.

#300 fix(logging): Silence stdout from IDF installation
  tools/install-esp-idf.sh
Labels: enhancement

#302 fix(docker): Fix docker image tagging
  .github/workflows/docker.yml
Labels: Docker

#303 feat(matter): removes CHIPOBLE to manage it case by case
  configs/defconfig.common
  configs/defconfig.esp32
  configs/defconfig.esp32c3
  configs/defconfig.esp32c5
  configs/defconfig.esp32c6
  configs/defconfig.esp32h2
  configs/defconfig.esp32s2
  configs/defconfig.esp32s3
  main/idf_component.yml
Labels: Type: Feature request
